In [13]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from scipy.stats import norm, skew
from scipy import stats
import statsmodels.api as sm
import seaborn as sns


from sklearn.ensemble import AdaBoostClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.preprocessing import LabelEncoder
from sklearn import metrics
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
##from xgboost.sklearn import XGBClassifier

In [2]:
idvfc = pd.read_csv("idvfc_marzo2022_limpio.csv", encoding='latin1')

In [3]:
to_drop = ['Tipo_de_delito','Entidad','Sexo']
idvfc.drop(to_drop, inplace =True , axis=1)

In [4]:
idvfc_dummies = pd.get_dummies(idvfc)
idvfc_dummies.head()

Año  Clave_Ent  Enero  Febrero  Marzo  Abril  Mayo  Junio  Julio  Agosto  \
0  2015          1      0        0      0    0.0   0.0    0.0    0.0     0.0   
1  2015          1      0        0      0    0.0   0.0    0.0    0.0     0.0   
2  2015          1      0        0      0    0.0   1.0    0.0    0.0     1.0   
3  2015          1      0        0      0    0.0   0.0    0.0    0.0     0.0   
4  2015          1      0        0      0    0.0   0.0    0.0    0.0     0.0   

   ...  Subtipo_de_delito_Lesiones dolosas  Subtipo_de_delito_Rapto  \
0  ...                                   0                        0   
1  ...                                   0                        0   
2  ...                                   0                        0   
3  ...                                   0                        0   
4  ...                                   1                        0   

   Modalidad_Con arma blanca  Modalidad_Con arma de fuego  \
0                          0                            1   
1                          1                            0   
2                          0                            0   
3                          0                            0   
4                          0                            1   

   Modalidad_Con otro elemento  Modalidad_No especificado  Modalidad_Rapto  \
0                            0                          0                0   
1                            0                          0                0   
2                            1                          0                0   
3                            0                          1                0   
4                            0                          0                0   

   Rango_de_edad_Adultos (18 y más)  Rango_de_edad_Menores de edad (0-17)  \
0                                  0                                     1   
1                                  0                                     1   
2                                  0                                     1   
3                                  0                                     1   
4                                  0                                     1   

   Rango_de_edad_No especificado  
0                              0  
1                              0  
2                              0  
3                              0  
4                              0  

[5 rows x 27 columns]

In [5]:
# We will use the data frame where we had created dummy variables
y = idvfc_dummies['Total'].values
X = idvfc_dummies.drop(columns = ['Total'])

In [6]:
# Scaling all the variables to a range of 0 to 1
from sklearn.preprocessing import MinMaxScaler
features = X.columns.values
scaler = MinMaxScaler(feature_range = (0,1))
scaler.fit(X)
X = pd.DataFrame(scaler.transform(X))
X.columns = features

In [7]:
from sklearn.model_selection import train_test_split
# Test split
x_train, x_test, y_train, y_test = train_test_split(X,y, test_size=0.3, random_state=0)

In [8]:
from sklearn.linear_model import LogisticRegression
logistic_Regression = LogisticRegression(max_iter=1000,random_state=0)
logistic_Regression.fit(x_train,y_train)

LogisticRegression(max_iter=1000, random_state=0)

In [33]:
y_pred = logistic_Regression.predict(x_test)

In [34]:
from sklearn.metrics import accuracy_score
log = accuracy_score(y_pred,y_test)*100
log

53.104138851802404

In [35]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_pred,y_test))

[[1591  284  173 ...    0    0    0]
 [   0    0    0 ...    0    0    0]
 [   0    0    0 ...    0    0    0]
 ...
 [   0    0    0 ...    0    0    0]
 [   0    0    0 ...    0    0    1]
 [   0    0    0 ...    0    0    0]]


In [36]:
#print(classification_report(y_pred,y_test))

In [37]:
gnb=GaussianNB()
gnb.fit(x_train,y_train)

GaussianNB()

In [38]:
pred_gnb = gnb.predict(x_test)

In [39]:
GNB = accuracy_score(pred_gnb,y_test)*100

In [40]:
print(confusion_matrix(pred_gnb,y_test))

[[1458    0    0 ...    0    0    0]
 [   0   45    0 ...    0    0    0]
 [   0    0    0 ...    0    0    0]
 ...
 [   0    0    0 ...    0    0    0]
 [   0    0    0 ...    0    0    0]
 [   0    0    0 ...    0    0    0]]


In [41]:
print(classification_report(pred_gnb,y_test))

              precision    recall  f1-score   support

         0.0       0.92      1.00      0.96      1458
         1.0       0.16      1.00      0.27        45
         2.0       0.00      0.00      0.00         0
         3.0       0.00      0.00      0.00         0
         4.0       0.00      0.00      0.00         0
         5.0       0.00      0.00      0.00         0
         6.0       0.00      0.00      0.00         0
         7.0       0.00      0.00      0.00         0
         8.0       0.00      0.00      0.00         0
         9.0       0.00      0.00      0.00         0
        10.0       0.00      0.00      0.00         0
        11.0       0.00      0.00      0.00        52
        12.0       0.00      0.00      0.00         0
        13.0       0.00      0.00      0.00         0
        14.0       0.00      0.00      0.00         0
        15.0       0.00      0.00      0.00         0
        16.0       0.00      0.00      0.00         0
        17.0       0.00    

/Users/esthephanyayala/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/esthephanyayala/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/esthephanyayala/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result

In [42]:
svc = SVC()
svc.fit(x_train,y_train)
pred_svc = svc.predict(x_test)

TypeError: 'numpy.float64' object is not callable

In [43]:
SVC = accuracy_score(pred_svc,y_test)*100

In [44]:
print(confusion_matrix(pred_svc,y_test))

[[1581  280  166 ...    1    0    1]
 [   1    1    1 ...    0    0    0]
 [   9    3    6 ...    0    0    0]
 ...
 [   0    0    0 ...    0    0    0]
 [   0    0    0 ...    0    0    0]
 [   0    0    0 ...    0    0    0]]


In [45]:
print(classification_report(pred_svc,y_test))

              precision    recall  f1-score   support

         0.0       0.99      0.54      0.70      2906
         1.0       0.00      0.14      0.01         7
         2.0       0.03      0.07      0.05        82
         3.0       0.00      0.00      0.00         0
         4.0       0.00      0.00      0.00         0
         5.0       0.00      0.00      0.00         0
         6.0       0.00      0.00      0.00         0
         7.0       0.00      0.00      0.00         0
         8.0       0.00      0.00      0.00         0
         9.0       0.00      0.00      0.00         0
        10.0       0.00      0.00      0.00         0
        11.0       0.00      0.00      0.00         0
        12.0       0.00      0.00      0.00         0
        13.0       0.00      0.00      0.00         0
        14.0       0.00      0.00      0.00         0
        15.0       0.00      0.00      0.00         0
        16.0       0.00      0.00      0.00         0
        17.0       0.00    

/Users/esthephanyayala/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/esthephanyayala/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/esthephanyayala/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result

In [46]:
dtree_en = DecisionTreeClassifier(criterion='entropy',splitter='random',max_leaf_nodes=5,min_samples_leaf=10,max_depth=3)

In [47]:
clf = dtree_en.fit(x_train,y_train)

In [48]:
pred_dt = clf.predict(x_test)

In [49]:
DTREE = accuracy_score(pred_dt,y_test)*100

In [50]:
cm=confusion_matrix(y_test,pred_dt)
print(cm)
print(classification_report(y_test,pred_dt))

[[1591    0    0 ...    0    0    0]
 [ 235   22   27 ...    0    0    0]
 [ 143   11   19 ...    0    0    0]
 ...
 [   1    0    0 ...    0    0    0]
 [   1    0    0 ...    0    0    0]
 [   1    0    0 ...    0    0    0]]
              precision    recall  f1-score   support

         0.0       0.62      1.00      0.76      1591
         1.0       0.17      0.08      0.11       284
         2.0       0.06      0.11      0.08       173
         3.0       0.00      0.00      0.00       108
         4.0       0.00      0.00      0.00        86
         5.0       0.00      0.00      0.00        59
         6.0       0.00      0.00      0.00        50
         7.0       0.00      0.00      0.00        35
         8.0       0.00      0.00      0.00        33
         9.0       0.00      0.00      0.00        27
        10.0       0.00      0.00      0.00        25
        11.0       0.00      0.00      0.00        25
        12.0       0.00      0.00      0.00        19
        13.0   

/Users/esthephanyayala/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/esthephanyayala/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/esthephanyayala/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, le

In [51]:
model = DecisionTreeClassifier(criterion='entropy',max_depth=1,random_state=0)
adaboost = AdaBoostClassifier(n_estimators=80, base_estimator=model,random_state=0)
adaboost.fit(x_train,y_train)

AdaBoostClassifier(base_estimator=DecisionTreeClassifier(criterion='entropy',
                                                         max_depth=1,
                                                         random_state=0),
                   n_estimators=80, random_state=0)

In [52]:
pred = adaboost.predict(x_test)

In [53]:
ada = accuracy_score(y_test,pred)*100

In [54]:
print("1)  Logistic Regression    :",log)
print("2)  AdaBoost - Entropy     :",ada)
print("3)  Decision Tree - Entropy:",DTREE)
print("4)  Naive-Bayes            :",GNB)
print("5) SVC                    :",SVC)

1)  Logistic Regression    : 53.104138851802404
2)  AdaBoost - Entropy     : 0.23364485981308408
3)  Decision Tree - Entropy: 54.47263017356475
4)  Naive-Bayes            : 50.300400534045394
5) SVC                    : 53.00400534045394
